### ISSUE TITLE
Multiplayer support

### ISSUE THREAD

**Issue by w3bb** [SmushyTaco/Hunger-Remover#1]
This doesn't seem to be working on multiplayer. 

Config:

```
{
  "disableMod": false,
  "eatInstantly": false,
  "foodCantStack": false,
  "cantSprint": true
}
```

**Comment by w3bb** [comment]
It seems to work actually, it just doesn't disable running.

**Comment by SmushyTaco** [comment]
![image](https://github.com/user-attachments/assets/b2b73fe1-ff32-43a4-8ad3-3a2a6b1a5eaa)

This is the new config and server client sync is handled automatically so now it should disable sprinting :)
