### ISSUE TITLE
Fabric 1.21 1.0.9

### ISSUE THREAD

**Issue by Mostovm** [SmushyTaco/Hunger-Remover#10]
Found no issues rather some ideas to implement.
-Food eaten returns more health depending on it's great quality. (Rotten flesh for some reason gives a good amount of health, I can just farm zombies and not worry about the better type of food items.)
-Alter max stack count on food.
-Add effect Stomach Full after eating x amount and over a period of time the count goes lower down to zero. After a threshold of eating too much players can't eat till x amount of second. An idea, configurable or so this one is a bit out there.

I'm glad this mod doesn't alter the armor's hud position and oxygen, I think that's silly.
Good mod but it would be nice for more configuration. Thank you.

**Comment by SmushyTaco** [comment]
The second suggestion may be implemented. Something regarding the first might be done too.

**Comment by SmushyTaco** [comment]
![image](https://github.com/user-attachments/assets/acaaaef2-48d5-4268-bf1d-28e1f1aaf47a)

Here's the new config in all it's glory!

**Comment by memphismc** [comment]
> ![image](https://private-user-images.githubusercontent.com/41648290/389256323-acaaaef2-48d5-4268-bf1d-28e1f1aaf47a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY2OTE5NTMsIm5iZiI6MTczNjY5MTY1MywicGF0aCI6Ii80MTY0ODI5MC8zODkyNTYzMjMtYWNhYWFlZjItNDhkNS00MjY4LWJmMWQtMjhlMWYxYWFmNDdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTEyVDE0MjA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhYjIxMjRhNjNmYTQ2MmUyMzM4N2I5ZjRjNzc1ODM5MmRjZTA1YjUyNjJmOGQ3ODVmZjkyMTNmYmI2ODNhNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.W_fIQUW4e5u0EM63HhTyNHwtAg5qQV8j5bsELv97MsA)
> 
> Here's the new config in all it's glory!

![image](https://github.com/user-attachments/assets/59562760-aad9-4e79-bafa-7d33f0df159c)

where is this config in 1.21.1 fabric...?
