### ISSUE TITLE
Config Option for gui

### ISSUE THREAD

**Issue by Simple205** [SmushyTaco/Hunger-Remover#2]
Can you add an option in the config to move the armor bars to the hunger bar spot? It doesn't look right with both heath and armor being stacked on one side of the hot bar and having the armor bar on the other side is nostalgic as well 
![image](https://user-images.githubusercontent.com/73256738/128156957-2dec42ba-04df-48bf-8ea4-0ac0dddf08f8.png)

**Comment by SmushyTaco** [comment]
I looked into it and this seems too complex to implement, if you want this to be done you're welcome to do it yourself and open a PR request.

**Comment by SmushyTaco** [comment]
![image](https://github.com/user-attachments/assets/b61a48ca-371f-40a1-902b-60bc11c07925)

I've implemented this! Enjoy :)
