### ISSUE TITLE
Incompatibility with Better Mount HUD

### ISSUE THREAD

**Issue by Anoaxx** [SmushyTaco/Hunger-Remover#4]
[latest.log](https://github.com/SmushyTaco/Hunger-Remover/files/8644879/latest.log)

I don't know if its on yours or Better Mount HUD end.

Link to issue on Better Mount HUD Gitlab: https://gitlab.com/Lortseam/better-mount-hud/-/issues/8

**Comment by Anoaxx** [comment]
If you want a crashlog just tell me

**Comment by SmushyTaco** [comment]
This should be fixed in the 1.20.1 release.
