### ISSUE TITLE
Creative Player can die from Negative Food Value

### ISSUE THREAD

**Issue by StellaBiscuit** [SmushyTaco/Hunger-Remover#5]
When you eat negative food value, it causes the player to take damage, but this also aply to Creative Players and can even kill them

Not just that, dying due to food doesn't send any death message, creative or survival

**Comment by SmushyTaco** [comment]
You haven't provided me with enough information, what food even has negative values? Is this a modded food item that there's a problem with?

I'm going to close this issue. if it's still an issue today then open a new ticket with more details and provide steps to reproduce this. Thank you.
